### PR TITLE
fixed table of contents

### PR DESCRIPTION
**Pull request by EitanBlumin**
Couple of fixes here:

- Fixed the link texts in the table of contents.
- In the PowerPoint slides, added mentions of the SSDT Refactor Tool in regards to renaming objects and expanding wildcards.

### CODE REVIEW

**Comment by way0utwest** [comment]
Thanks for the typo fix. Appreciate this. I was trying to get this done in a hurry.

However, I'm not taking PRs for the PPT. You can let me know what you think should be in there, but I don't have a good way to review this from the PR and would prefer to keep control of the deck.

**Comment by EitanBlumin** [comment]
Sure thing.
In the slides that talk about renaming columns, there are some recommendations but they ignore the existence of the Refractor Tool in SSDT which makes this operation very easy.

**Comment by way0utwest** [comment]
Easy but not necessarily zero downtime. Multiple deployments are needed to coordinate with clients and ssdt didn't make that easy

**Comment by EitanBlumin** [comment]
Sure it did make it easy.
Have you used the refactor tool in SSDT before for renaming objects?

It does the change very easily using `sp_rename` automatically.
No multiple deployments are needed. Just one go.

**Comment by way0utwest** [comment]
Easy renames don't make for zero downtime. You'd have to see the talk.

It is easy, and it works.

**Comment by EitanBlumin** [comment]
Yeah, I'd love to see the talk regardless. Sorry that I missed it.
I'm guessing that it has something to do with dependent objects? Or maybe dependent app code?

**Comment by way0utwest** [comment]
You got it.
The demo in the 40_rename doesn't work well. Breaks dependent objects.

**Comment by EitanBlumin** [comment]
Of course. But that was not generated by the Refactor Tool in SSDT.

The Refactor Tool in SSDT also takes care of dependencies automatically.

**Comment by way0utwest** [comment]
still not zero downtime. I am not adding that to the talk, because it would imply something I don't want to imply.

**Comment by EitanBlumin** [comment]
I understand.

**Comment by EitanBlumin** [comment]
I reverted the PPT.

**Comment by way0utwest** [comment]
תודה

**Pull request merged**
